export interface Hotel {
  slug: string
  name: string
  image: string
  images: string[]
  rating: number
  ratingText: string
  reviews: number
  stars: number
  location: string
  locationDetail: string
  distanceCenter: string
  badges: string[]
  mealPlan: string
  pricePerPerson: number
  hasDiscount: boolean
  roomType: string
  description: string
  amenities: string[]
  policies: string[]
  locationDescription: string
  reviewSummary: string
  checkIn: string
  checkOut: string
}

export interface Destination {
  name: string
  country: string
  airport: string
  selectedHotel: Hotel & { flightRoute: string }
  hotels: Hotel[]
  convenientDates: { nights: number; checkIn: string; checkOut: string; price: number }[]
}

export const destinationData: Record<string, Destination> = {
  cancun: {
    name: "Cancún",
    country: "México",
    airport: "CUN",
    selectedHotel: {
      slug: "beachscape-kin-ha",
      name: "Hotel Beachscape Kin Ha",
      image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&h=400&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&h=500&fit=crop",
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
      ],
      rating: 7.3,
      ratingText: "Confortable",
      reviews: 1416,
      stars: 3,
      location: "Frente a la playa. Zona Hotelera, Cancún",
      locationDetail: "Cancún, México",
      distanceCenter: "A 3,50 km del centro",
      badges: ["Elegido por parejas", "Early check in y más"],
      mealPlan: "Desayuno",
      pricePerPerson: 450,
      hasDiscount: false,
      roomType: "Habitación Doble Estándar",
      flightRoute: "LIM ⇄ CUN",
      description: "Hotel Beachscape Kin Ha se sitúa en la Zona Hotelera de Cancún. Cuenta con piscina al aire libre todo el año, wi-fi gratis en zonas comunes y servicio de masajes, además de estacionamiento gratis.\n\nNecesitas saber:\n• Mascotas: no se admiten\n\nEl alojamiento sirve diariamente el desayuno, el cual se ofrece en el restaurante. El personal de la propiedad proporcionará servicio a la habitación.\n\nLas comodidades incluyen gimnasio, recepción 24 hrs, terraza y jardín. Los huéspedes también podrán disfrutar de solárium y ascensor.\n\nRegistro Nacional de Turismo: 42871",
      amenities: ["Restaurante", "Piscina al aire libre todo el año", "Servicio de masajes", "Estacionamiento gratis", "Aire acondicionado en zonas comunes", "Piscina", "Wi-Fi gratis en zonas comunes"],
      policies: ["Check-in: 15:00", "Check-out: 12:00"],
      locationDescription: "Ubicado frente al mar en la Zona Hotelera, con playas a pocos pasos. Cercano a centros comerciales y vida nocturna. La zona cuenta con una amplia oferta de restaurantes y actividades acuáticas.",
      reviewSummary: "El hotel ofrece una excelente atención y habitaciones cómodas con vista al mar. Los huéspedes destacan la ubicación privilegiada...",
      checkIn: "15:00",
      checkOut: "12:00",
    },
    hotels: [
      {
        slug: "grand-oasis-cancun",
        name: "Grand Oasis Cancún",
        image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
        ],
        rating: 9.3,
        ratingText: "Excelente",
        reviews: 1840,
        stars: 4,
        location: "Próximo a la playa. Boulevard Kukulcán, Cancún",
        locationDetail: "Cancún, México",
        distanceCenter: "A 2,10 km del centro",
        badges: ["Oferta imbatible"],
        mealPlan: "Desayuno buffet",
        pricePerPerson: 558,
        hasDiscount: true,
        roomType: "Habitación Doble Superior",
        description: "Grand Oasis Cancún es un resort todo incluido ubicado en el corazón de la Zona Hotelera. Ofrece múltiples piscinas, spa de clase mundial y una variada oferta gastronómica con más de 10 restaurantes.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Se requiere depósito al check-in\n\nEl resort cuenta con entretenimiento en vivo todas las noches, club de playa privado y actividades acuáticas. Los huéspedes disfrutan de acceso ilimitado a todas las instalaciones.\n\nRegistro Nacional de Turismo: 38291",
        amenities: ["Restaurante", "Piscina al aire libre todo el año", "Spa completo", "Estacionamiento gratis", "Aire acondicionado", "Bar en la piscina", "Wi-Fi gratis"],
        policies: ["Check-in: 15:00", "Check-out: 11:00"],
        locationDescription: "Ubicado en Boulevard Kukulcán con acceso directo a la playa. A pocos minutos de las principales atracciones turísticas y centros comerciales de la zona.",
        reviewSummary: "Los huéspedes destacan la variedad gastronómica y las instalaciones de primer nivel. El servicio al cliente es excepcional...",
        checkIn: "15:00",
        checkOut: "11:00",
      },
      {
        slug: "hotel-cancun-plaza",
        name: "Hotel Cancún Plaza",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
        ],
        rating: 8.2,
        ratingText: "Muy bueno",
        reviews: 8163,
        stars: 4,
        location: "Frente al mar, cerca de Playa Delfines. Cancún",
        locationDetail: "Cancún, México",
        distanceCenter: "A 1,80 km del centro",
        badges: ["Oferta imbatible"],
        mealPlan: "Desayuno",
        pricePerPerson: 601,
        hasDiscount: true,
        roomType: "Habitación Doble Estándar",
        description: "Hotel Cancún Plaza se encuentra frente al mar con vistas espectaculares. Cuenta con piscina infinita, restaurante gourmet y acceso directo a la playa.\n\nNecesitas saber:\n• Mascotas: no se admiten\n\nEl alojamiento ofrece desayuno diario incluido. Las instalaciones incluyen gimnasio, sala de conferencias y servicio de conserjería.\n\nRegistro Nacional de Turismo: 45623",
        amenities: ["Restaurante", "Piscina infinita", "Gimnasio", "Estacionamiento gratis", "Aire acondicionado", "Piscina", "Wi-Fi gratis en zonas comunes"],
        policies: ["Check-in: 14:00", "Check-out: 12:00"],
        locationDescription: "Ubicación privilegiada frente a Playa Delfines, una de las playas más hermosas de Cancún. Cerca de restaurantes y tiendas.",
        reviewSummary: "Hotel con excelente relación calidad-precio. Los huéspedes valoran la vista al mar y la limpieza de las habitaciones...",
        checkIn: "14:00",
        checkOut: "12:00",
      },
      {
        slug: "hyatt-zilara-cancun",
        name: "Hyatt Zilara Cancún",
        image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
        ],
        rating: 8.6,
        ratingText: "Muy bueno",
        reviews: 2391,
        stars: 5,
        location: "Frente a la playa. Zona Hotelera, Cancún",
        locationDetail: "Cancún, México",
        distanceCenter: "A 4,20 km del centro",
        badges: [],
        mealPlan: "All inclusive",
        pricePerPerson: 734,
        hasDiscount: true,
        roomType: "Suite Junior Vista al Mar",
        description: "Hyatt Zilara Cancún es un resort solo para adultos con todo incluido de lujo. Ofrece suites elegantes con vista al mar, spa holístico y gastronomía de clase mundial.\n\nNecesitas saber:\n• Solo adultos (18+)\n• Mascotas: no se admiten\n\nEl resort cuenta con 5 restaurantes, 4 bares y una extensa playa privada. Las comodidades incluyen spa, fitness center y actividades acuáticas.\n\nRegistro Nacional de Turismo: 51234",
        amenities: ["Restaurante", "Piscina al aire libre", "Spa completo", "Estacionamiento gratis", "Aire acondicionado", "Bar en la playa", "Wi-Fi gratis"],
        policies: ["Check-in: 15:00", "Check-out: 11:00"],
        locationDescription: "Resort de lujo en la Zona Hotelera con playa privada. Rodeado de los mejores restaurantes y centros de entretenimiento de Cancún.",
        reviewSummary: "Resort excepcional para parejas. Servicio impecable, comida deliciosa y playas espectaculares. Altamente recomendado...",
        checkIn: "15:00",
        checkOut: "11:00",
      },
      {
        slug: "fiesta-americana-cancun",
        name: "Fiesta Americana Cancún",
        image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
        ],
        rating: 8.2,
        ratingText: "Muy bueno",
        reviews: 2824,
        stars: 5,
        location: "Cercano a Zona Arqueológica. Cancún",
        locationDetail: "Cancún, México",
        distanceCenter: "A 5,00 km del centro",
        badges: [],
        mealPlan: "All inclusive",
        pricePerPerson: 997,
        hasDiscount: false,
        roomType: "Suite Premium",
        description: "Fiesta Americana Cancún ofrece una experiencia todo incluido de primer nivel. El resort combina lujo moderno con la belleza natural del Caribe mexicano.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Check-in express disponible\n\nCuenta con múltiples restaurantes temáticos, bares, piscinas y actividades para todas las edades. El spa ofrece tratamientos exclusivos con productos locales.\n\nRegistro Nacional de Turismo: 29847",
        amenities: ["Restaurante", "Piscina al aire libre", "Spa", "Estacionamiento gratis", "Aire acondicionado", "Kids club", "Wi-Fi gratis"],
        policies: ["Check-in: 16:00", "Check-out: 12:00"],
        locationDescription: "Cercano a zonas arqueológicas mayas. Ofrece fácil acceso a excursiones culturales y actividades ecoturísticas en la región.",
        reviewSummary: "Excelente resort familiar con instalaciones de primera. La comida es variada y de buena calidad. Personal muy atento...",
        checkIn: "16:00",
        checkOut: "12:00",
      },
    ],
    convenientDates: [
      { nights: 5, checkIn: "lunes 24 Ago", checkOut: "sábado 29 Ago", price: 373 },
      { nights: 5, checkIn: "sábado 22 Ago", checkOut: "jueves 27 Ago", price: 373 },
      { nights: 5, checkIn: "viernes 21 Ago", checkOut: "miércoles 26 Ago", price: 387 },
      { nights: 4, checkIn: "lunes 21 Set", checkOut: "viernes 25 Set", price: 363 },
    ],
  },
  cartagena: {
    name: "Cartagena",
    country: "Colombia",
    airport: "CTG",
    selectedHotel: {
      slug: "aixo-suites",
      name: "Hotel Aixo Suites By Geh Suites",
      image: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600&h=400&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&h=500&fit=crop",
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=500&h=350&fit=crop",
      ],
      rating: 7.3,
      ratingText: "Confortable",
      reviews: 362,
      stars: 3,
      location: "Frente a la playa. Cartagena de Indias",
      locationDetail: "Cartagena de Indias, Colombia",
      distanceCenter: "A 2,70 km del centro",
      badges: ["Elegido por parejas", "Early check in y más"],
      mealPlan: "Desayuno",
      pricePerPerson: 499,
      hasDiscount: false,
      roomType: "Habitación Doble Estándar",
      flightRoute: "LIM ⇄ CTG",
      description: "Hotel Aixo Suites By Geh Suites se sitúa en Cartagena de Indias. Cuenta con piscina al aire libre todo el año, wi-fi gratis en zonas comunes y servicio de masajes, además de estacionamiento gratis.\n\nNecesitas saber:\n• Mascotas: no se admiten\n\nEl alojamiento sirve diariamente el desayuno, el cual se ofrece en el restaurante. El personal de la propiedad proporcionará servicio a la habitación.\n\nLas comodidades incluyen gimnasio, recepción 24 hrs, terraza y jardín. Los huéspedes también podrán disfrutar de solárium y ascensor.\n\nRegistro Nacional de Turismo: 53491",
      amenities: ["Restaurante", "Piscina al aire libre todo el año", "Servicio de masajes", "Estacionamiento gratis", "Aire acondicionado en zonas comunes", "Piscina", "Wi-Fi gratis en zonas comunes"],
      policies: ["Check-in: 15:00", "Check-out: 12:00"],
      locationDescription: "Ubicado frente al mar, con playas a media cuadra, facilita el acceso a actividades náuticas. Cercano al centro de la ciudad y al Castillo de San Felipe de Barajas, permite explorar la rica historia de la zona. La zona cuenta con una amplia oferta de comercios y restaurantes.",
      reviewSummary: "El hotel ofrece una excelente atención y habitaciones cómodas con vista ¿...",
      checkIn: "15:00",
      checkOut: "12:00",
    },
    hotels: [
      {
        slug: "oz-hotel-luxury",
        name: "OZ Hotel Luxury",
        image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=500&h=350&fit=crop",
        ],
        rating: 9.3,
        ratingText: "Excelente",
        reviews: 1840,
        stars: 4,
        location: "Próximo a la playa Bocagrande. Cartagena de Indias",
        locationDetail: "Cartagena de Indias, Colombia",
        distanceCenter: "A 1,50 km del centro",
        badges: ["Oferta imbatible"],
        mealPlan: "Desayuno buffet",
        pricePerPerson: 558,
        hasDiscount: true,
        roomType: "Habitación Doble Superior",
        description: "OZ Hotel Luxury es un moderno hotel de 4 estrellas ubicado en el exclusivo barrio de Bocagrande. Ofrece habitaciones elegantes con vista al mar, piscina en la azotea y restaurante gourmet.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Se requiere tarjeta de crédito al check-in\n\nEl hotel cuenta con spa, centro de fitness y servicio de conserjería 24 horas. El desayuno buffet incluye opciones internacionales y locales.\n\nRegistro Nacional de Turismo: 48723",
        amenities: ["Restaurante", "Piscina en azotea", "Spa", "Estacionamiento gratis", "Aire acondicionado", "Bar", "Wi-Fi gratis"],
        policies: ["Check-in: 15:00", "Check-out: 11:00"],
        locationDescription: "Ubicado en Bocagrande, la zona más exclusiva de Cartagena. A pasos de la playa y cerca de restaurantes de primer nivel, tiendas y vida nocturna.",
        reviewSummary: "Hotel de lujo con excelente servicio. La piscina en la azotea ofrece vistas espectaculares. Habitaciones modernas y confortables...",
        checkIn: "15:00",
        checkOut: "11:00",
      },
      {
        slug: "hotel-cartagena-plaza",
        name: "Hotel Cartagena Plaza",
        image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=500&h=350&fit=crop",
        ],
        rating: 8.2,
        ratingText: "Muy bueno",
        reviews: 8163,
        stars: 4,
        location: "Frente al mar, cerca de Bocagrande. Cartagena de Indias",
        locationDetail: "Cartagena de Indias, Colombia",
        distanceCenter: "A 2,00 km del centro",
        badges: ["Oferta imbatible"],
        mealPlan: "Desayuno",
        pricePerPerson: 601,
        hasDiscount: true,
        roomType: "Habitación Doble Estándar",
        description: "Hotel Cartagena Plaza se encuentra frente al mar con acceso directo a la playa. Ofrece amplias habitaciones, piscina al aire libre y restaurante con cocina caribeña.\n\nNecesitas saber:\n• Mascotas: no se admiten\n\nEl hotel dispone de salón de eventos, centro de negocios y servicio de transporte al aeropuerto. Ideal para viajeros de negocios y placer.\n\nRegistro Nacional de Turismo: 39215",
        amenities: ["Restaurante", "Piscina al aire libre", "Centro de negocios", "Estacionamiento gratis", "Aire acondicionado", "Piscina", "Wi-Fi gratis en zonas comunes"],
        policies: ["Check-in: 14:00", "Check-out: 12:00"],
        locationDescription: "Frente al mar en Bocagrande. Acceso directo a la playa y cerca de centros comerciales. A pocos minutos del centro histórico en taxi.",
        reviewSummary: "Excelente ubicación frente al mar. Las habitaciones son amplias y cómodas. El personal es muy amable y servicial...",
        checkIn: "14:00",
        checkOut: "12:00",
      },
      {
        slug: "americas-casa-de-playa",
        name: "Americas Casa de Playa",
        image: "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=500&h=350&fit=crop",
        ],
        rating: 8.6,
        ratingText: "Muy bueno",
        reviews: 2391,
        stars: 5,
        location: "Frente a la playa. Cartagena de Indias",
        locationDetail: "Cartagena de Indias, Colombia",
        distanceCenter: "A 3,50 km del centro",
        badges: [],
        mealPlan: "Desayuno",
        pricePerPerson: 734,
        hasDiscount: true,
        roomType: "Suite Vista al Mar",
        description: "Americas Casa de Playa es un resort de playa con acceso directo al mar Caribe. Cuenta con amplios jardines tropicales, múltiples piscinas y una extensa oferta gastronómica.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Reserva flexible disponible\n\nEl resort ofrece actividades acuáticas, club infantil y entretenimiento nocturno. Las habitaciones cuentan con balcón privado y vista al mar.\n\nRegistro Nacional de Turismo: 56789",
        amenities: ["Restaurante", "Piscina al aire libre", "Actividades acuáticas", "Estacionamiento gratis", "Aire acondicionado", "Club infantil", "Wi-Fi gratis"],
        policies: ["Check-in: 15:00", "Check-out: 11:00"],
        locationDescription: "Resort frente a la playa con acceso directo al mar. Rodeado de naturaleza tropical, ideal para familias y parejas que buscan tranquilidad.",
        reviewSummary: "Resort espectacular con playas hermosas. Las piscinas y jardines son increíbles. Excelente servicio y comida de calidad...",
        checkIn: "15:00",
        checkOut: "11:00",
      },
      {
        slug: "estelar-playa-manzanillo",
        name: "Estelar Playa Manzanillo - All Inclusive",
        image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?w=500&h=350&fit=crop",
        ],
        rating: 8.2,
        ratingText: "Muy bueno",
        reviews: 2824,
        stars: 5,
        location: "Cercano a Ciudad Amurallada. Cartagena de Indias",
        locationDetail: "Cartagena de Indias, Colombia",
        distanceCenter: "A 4,00 km del centro",
        badges: [],
        mealPlan: "All inclusive",
        pricePerPerson: 997,
        hasDiscount: false,
        roomType: "Suite Premium All Inclusive",
        description: "Estelar Playa Manzanillo es un resort todo incluido ubicado en una playa privada. Ofrece una experiencia completa con gastronomía, bebidas, entretenimiento y actividades acuáticas incluidas.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Todo incluido: comidas, bebidas y actividades\n\nEl resort cuenta con spa, gimnasio, canchas deportivas y club de playa. Ideal para unas vacaciones sin preocupaciones.\n\nRegistro Nacional de Turismo: 61234",
        amenities: ["Restaurante", "Piscina al aire libre", "Spa", "Todo incluido", "Aire acondicionado", "Deportes acuáticos", "Wi-Fi gratis"],
        policies: ["Check-in: 15:00", "Check-out: 12:00"],
        locationDescription: "Cercano a la Ciudad Amurallada de Cartagena, patrimonio de la humanidad. Fácil acceso para explorar la historia y cultura de la ciudad.",
        reviewSummary: "Excelente experiencia todo incluido. La playa privada es hermosa y las instalaciones están muy bien mantenidas...",
        checkIn: "15:00",
        checkOut: "12:00",
      },
    ],
    convenientDates: [
      { nights: 5, checkIn: "lunes 24 Ago", checkOut: "sábado 29 Ago", price: 373 },
      { nights: 5, checkIn: "sábado 22 Ago", checkOut: "jueves 27 Ago", price: 373 },
      { nights: 5, checkIn: "viernes 21 Ago", checkOut: "miércoles 26 Ago", price: 387 },
      { nights: 4, checkIn: "lunes 21 Set", checkOut: "viernes 25 Set", price: 363 },
    ],
  },
  cusco: {
    name: "Cusco",
    country: "Perú",
    airport: "CUZ",
    selectedHotel: {
      slug: "jose-antonio-cusco",
      name: "Hotel José Antonio Cusco",
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop",
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
      ],
      rating: 8.1,
      ratingText: "Muy bueno",
      reviews: 2100,
      stars: 4,
      location: "Centro Histórico, Cusco",
      locationDetail: "Cusco, Perú",
      distanceCenter: "A 0,50 km del centro",
      badges: ["Elegido por parejas"],
      mealPlan: "Desayuno",
      pricePerPerson: 220,
      hasDiscount: false,
      roomType: "Habitación Doble Estándar",
      flightRoute: "LIM ⇄ CUZ",
      description: "Hotel José Antonio Cusco se ubica en el Centro Histórico. Ofrece habitaciones confortables con calefacción y wifi gratis. Incluye desayuno buffet andino.\n\nNecesitas saber:\n• Mascotas: no se admiten\n• Servicio de oxígeno disponible para la altura\n\nRegistro Nacional de Turismo: 34521",
      amenities: ["Restaurante", "Calefacción", "Servicio de oxígeno", "Wi-Fi gratis", "Bar", "Recepción 24h", "Lavandería"],
      policies: ["Check-in: 14:00", "Check-out: 11:00"],
      locationDescription: "En el corazón del Centro Histórico de Cusco, a pasos de la Plaza de Armas y los principales sitios turísticos.",
      reviewSummary: "Hotel con excelente ubicación en el centro de Cusco. El servicio de oxígeno es muy útil para la aclimatación...",
      checkIn: "14:00",
      checkOut: "11:00",
    },
    hotels: [
      {
        slug: "palacio-del-inka",
        name: "Palacio del Inka",
        image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
        ],
        rating: 9.1, ratingText: "Excelente", reviews: 3200, stars: 5,
        location: "Plaza de Armas, Cusco", locationDetail: "Cusco, Perú", distanceCenter: "A 0,10 km del centro",
        badges: ["Oferta imbatible"], mealPlan: "Desayuno buffet", pricePerPerson: 380, hasDiscount: true,
        roomType: "Suite Colonial",
        description: "Palacio del Inka es un hotel de lujo en un edificio colonial del siglo XVI. Ofrece una experiencia única con decoración histórica y comodidades modernas.\n\nRegistro Nacional de Turismo: 12345",
        amenities: ["Restaurante", "Spa", "Bar", "Wi-Fi gratis", "Calefacción", "Conserjería", "Jardín interior"],
        policies: ["Check-in: 15:00", "Check-out: 12:00"],
        locationDescription: "Frente a la Plaza de Armas, en el corazón histórico de Cusco.",
        reviewSummary: "Hotel espectacular en un edificio histórico. El spa y restaurante son de primer nivel...",
        checkIn: "15:00", checkOut: "12:00",
      },
      {
        slug: "casa-andina-premium",
        name: "Casa Andina Premium Cusco",
        image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
        ],
        rating: 8.5, ratingText: "Muy bueno", reviews: 4500, stars: 4,
        location: "Centro Histórico, Cusco", locationDetail: "Cusco, Perú", distanceCenter: "A 0,30 km del centro",
        badges: ["Oferta imbatible"], mealPlan: "Desayuno", pricePerPerson: 310, hasDiscount: true,
        roomType: "Habitación Superior",
        description: "Casa Andina Premium ofrece una estancia cómoda en el centro histórico con arquitectura colonial restaurada.\n\nRegistro Nacional de Turismo: 23456",
        amenities: ["Restaurante", "Bar", "Wi-Fi gratis", "Calefacción", "Recepción 24h", "Oxígeno", "Lavandería"],
        policies: ["Check-in: 14:00", "Check-out: 11:00"],
        locationDescription: "En el centro histórico, a pasos de iglesias coloniales y museos.",
        reviewSummary: "Hotel confortable con excelente desayuno y servicio atento...",
        checkIn: "14:00", checkOut: "11:00",
      },
      {
        slug: "belmond-monasterio",
        name: "Belmond Hotel Monasterio",
        image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
        ],
        rating: 9.4, ratingText: "Excelente", reviews: 1800, stars: 5,
        location: "Barrio San Blas, Cusco", locationDetail: "Cusco, Perú", distanceCenter: "A 0,40 km del centro",
        badges: [], mealPlan: "Desayuno buffet", pricePerPerson: 520, hasDiscount: true,
        roomType: "Suite Monasterio",
        description: "Belmond Hotel Monasterio es un hotel de lujo en un monasterio del siglo XVI con claustros y jardines históricos.\n\nRegistro Nacional de Turismo: 34567",
        amenities: ["Restaurante", "Spa", "Capilla", "Wi-Fi gratis", "Calefacción", "Jardín claustro", "Oxígeno enriquecido"],
        policies: ["Check-in: 15:00", "Check-out: 11:00"],
        locationDescription: "En el bohemio barrio de San Blas, rodeado de galerías de arte y talleres artesanales.",
        reviewSummary: "Una experiencia única en un monasterio histórico. Servicio de clase mundial...",
        checkIn: "15:00", checkOut: "11:00",
      },
      {
        slug: "sonesta-cusco",
        name: "Sonesta Hotel Cusco",
        image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
        ],
        rating: 7.8, ratingText: "Bueno", reviews: 1500, stars: 3,
        location: "Av. Sol, Cusco", locationDetail: "Cusco, Perú", distanceCenter: "A 0,80 km del centro",
        badges: [], mealPlan: "Desayuno", pricePerPerson: 195, hasDiscount: false,
        roomType: "Habitación Estándar",
        description: "Sonesta Hotel Cusco ofrece habitaciones prácticas y confortables en la Avenida Sol, una de las principales vías de Cusco.\n\nRegistro Nacional de Turismo: 45678",
        amenities: ["Restaurante", "Wi-Fi gratis", "Calefacción", "Recepción 24h", "Lavandería", "Estacionamiento", "Bar"],
        policies: ["Check-in: 14:00", "Check-out: 11:00"],
        locationDescription: "Sobre la Avenida Sol, principal arteria comercial de Cusco, con fácil acceso a transporte.",
        reviewSummary: "Buena relación calidad-precio. Ubicación práctica para recorrer la ciudad...",
        checkIn: "14:00", checkOut: "11:00",
      },
    ],
    convenientDates: [
      { nights: 4, checkIn: "viernes 15 Ago", checkOut: "martes 19 Ago", price: 195 },
      { nights: 5, checkIn: "lunes 18 Ago", checkOut: "sábado 23 Ago", price: 220 },
      { nights: 3, checkIn: "sábado 23 Ago", checkOut: "martes 26 Ago", price: 175 },
      { nights: 4, checkIn: "viernes 29 Ago", checkOut: "martes 2 Set", price: 210 },
    ],
  },
  "rio-de-janeiro": {
    name: "Río de Janeiro",
    country: "Brasil",
    airport: "GIG",
    selectedHotel: {
      slug: "windsor-atlantica",
      name: "Windsor Atlantica Hotel",
      image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=400&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=500&fit=crop",
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
      ],
      rating: 8.5,
      ratingText: "Muy bueno",
      reviews: 3400,
      stars: 4,
      location: "Copacabana, Río de Janeiro",
      locationDetail: "Río de Janeiro, Brasil",
      distanceCenter: "A 5,00 km del centro",
      badges: ["Elegido por parejas", "Vista al mar"],
      mealPlan: "Desayuno",
      pricePerPerson: 520,
      hasDiscount: false,
      roomType: "Habitación Doble Vista Mar",
      flightRoute: "LIM ⇄ GIG",
      description: "Windsor Atlantica Hotel ofrece una ubicación privilegiada en Copacabana con vista directa al mar. Habitaciones modernas y piscina en la azotea.\n\nRegistro Nacional de Turismo: 78901",
      amenities: ["Restaurante", "Piscina en azotea", "Gimnasio", "Wi-Fi gratis", "Bar", "Sauna", "Estacionamiento"],
      policies: ["Check-in: 14:00", "Check-out: 12:00"],
      locationDescription: "En la icónica Copacabana, frente a la playa. A minutos del Pan de Azúcar y la vida nocturna carioca.",
      reviewSummary: "Hotel con ubicación espectacular en Copacabana. La piscina en la azotea ofrece vistas impresionantes...",
      checkIn: "14:00",
      checkOut: "12:00",
    },
    hotels: [
      {
        slug: "belmond-copacabana",
        name: "Belmond Copacabana Palace",
        image: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
        ],
        rating: 9.5, ratingText: "Excelente", reviews: 5200, stars: 5,
        location: "Copacabana Beach, Río de Janeiro", locationDetail: "Río de Janeiro, Brasil", distanceCenter: "A 4,50 km del centro",
        badges: ["Oferta imbatible"], mealPlan: "Desayuno buffet", pricePerPerson: 890, hasDiscount: true,
        roomType: "Suite Palace",
        description: "El icónico Belmond Copacabana Palace es símbolo de lujo en Río de Janeiro desde 1923.\n\nRegistro Nacional de Turismo: 00123",
        amenities: ["Restaurante", "Piscina", "Spa", "Wi-Fi gratis", "Bar", "Teatro", "Fitness center"],
        policies: ["Check-in: 15:00", "Check-out: 12:00"],
        locationDescription: "El hotel más emblemático de Copacabana, frente a la playa.",
        reviewSummary: "Un ícono del lujo en Río. Servicio impecable y ubicación inmejorable...",
        checkIn: "15:00", checkOut: "12:00",
      },
      {
        slug: "fasano-rio",
        name: "Hotel Fasano Río",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
        ],
        rating: 9.0, ratingText: "Excelente", reviews: 2100, stars: 5,
        location: "Ipanema, Río de Janeiro", locationDetail: "Río de Janeiro, Brasil", distanceCenter: "A 6,00 km del centro",
        badges: ["Oferta imbatible"], mealPlan: "Desayuno", pricePerPerson: 780, hasDiscount: true,
        roomType: "Habitación Deluxe Vista Mar",
        description: "Hotel Fasano Río combina diseño contemporáneo con elegancia clásica frente a la playa de Ipanema.\n\nRegistro Nacional de Turismo: 00234",
        amenities: ["Restaurante", "Piscina en azotea", "Spa", "Wi-Fi gratis", "Bar", "Gimnasio", "Playa"],
        policies: ["Check-in: 15:00", "Check-out: 12:00"],
        locationDescription: "En la exclusiva Ipanema, frente a una de las playas más famosas del mundo.",
        reviewSummary: "Diseño sofisticado y servicio excepcional. La piscina con vista al mar es espectacular...",
        checkIn: "15:00", checkOut: "12:00",
      },
      {
        slug: "arena-ipanema",
        name: "Arena Ipanema Hotel",
        image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=500&h=350&fit=crop",
        ],
        rating: 8.3, ratingText: "Muy bueno", reviews: 3800, stars: 4,
        location: "Ipanema Beach, Río de Janeiro", locationDetail: "Río de Janeiro, Brasil", distanceCenter: "A 6,20 km del centro",
        badges: [], mealPlan: "Desayuno", pricePerPerson: 620, hasDiscount: true,
        roomType: "Habitación Superior",
        description: "Arena Ipanema Hotel ofrece confort moderno a pasos de la playa de Ipanema.\n\nRegistro Nacional de Turismo: 00345",
        amenities: ["Restaurante", "Wi-Fi gratis", "Bar", "Gimnasio", "Lavandería", "Recepción 24h", "Estacionamiento"],
        policies: ["Check-in: 14:00", "Check-out: 11:00"],
        locationDescription: "A media cuadra de la playa de Ipanema, rodeado de tiendas y restaurantes.",
        reviewSummary: "Excelente relación calidad-precio en Ipanema. Habitaciones limpias y personal amable...",
        checkIn: "14:00", checkOut: "11:00",
      },
      {
        slug: "miramar-windsor",
        name: "Miramar Hotel by Windsor",
        image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=400&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500&h=350&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&h=350&fit=crop",
        ],
        rating: 8.7, ratingText: "Muy bueno", reviews: 2900, stars: 5,
        location: "Copacabana, Río de Janeiro", locationDetail: "Río de Janeiro, Brasil", distanceCenter: "A 5,00 km del centro",
        badges: [], mealPlan: "All inclusive", pricePerPerson: 950, hasDiscount: false,
        roomType: "Suite Premium",
        description: "Miramar Hotel by Windsor es un hotel boutique de lujo con diseño moderno frente a Copacabana.\n\nRegistro Nacional de Turismo: 00456",
        amenities: ["Restaurante", "Piscina en azotea", "Spa", "Wi-Fi gratis", "Bar panorámico", "Gimnasio", "Sauna"],
        policies: ["Check-in: 15:00", "Check-out: 12:00"],
        locationDescription: "Frente a la playa de Copacabana con vistas panorámicas al mar y al Pan de Azúcar.",
        reviewSummary: "Hotel boutique de primer nivel. El bar panorámico en la azotea es imperdible...",
        checkIn: "15:00", checkOut: "12:00",
      },
    ],
    convenientDates: [
      { nights: 5, checkIn: "lunes 25 Ago", checkOut: "sábado 30 Ago", price: 480 },
      { nights: 5, checkIn: "viernes 22 Ago", checkOut: "miércoles 27 Ago", price: 490 },
      { nights: 4, checkIn: "sábado 30 Ago", checkOut: "miércoles 3 Set", price: 430 },
      { nights: 5, checkIn: "viernes 5 Set", checkOut: "miércoles 10 Set", price: 470 },
    ],
  },
}

export function findHotel(destSlug: string, hotelSlug: string): { destination: Destination; hotel: Hotel & { flightRoute?: string } } | null {
  const dest = destinationData[destSlug]
  if (!dest) return null

  if (dest.selectedHotel.slug === hotelSlug) {
    return { destination: dest, hotel: dest.selectedHotel }
  }

  const found = dest.hotels.find((h) => h.slug === hotelSlug)
  if (!found) return null

  return { destination: dest, hotel: { ...found, flightRoute: `LIM ⇄ ${dest.airport}` } }
}
